# Generated by Django 2.2.2 on 2019-07-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='queryinfo',
            table='queryinfo',
        ),
    ]
